trigger:
  branches:
    include:
      - main
  paths:
    include:
      - search-index/*
      - azure-pipelines-search.yml

variables:
  vmImageName: ubuntu-latest
  docsContianerName: 'documents'

pool:
  vmImage: $(vmImageName)

steps:
- task: AzureKeyVault@1
  displayName: 'Get Secrets'
  inputs:
    azureSubscription: 'azure-knowledge-mining-arm-connection'
    KeyVaultName: '$(KEYVAULT)'
    SecretsFilter: '*'
    RunAsPreJob: false

- task: Bash@3
  displayName: 'Configure Azure Search'
  inputs:
    filePath: 'search-index/deploy.sh'
    arguments: '"$(System.DefaultWorkingDirectory)/search-index" "$(STORAGEACCOUNTSECRET)" "$(docsContianerName)" "$(SEARCHSERVICEENDPOINT)" "$(SEARCHSERVICESECRET)" "$(COGNITIVESERVICESSECRET)"'
